### ISSUE TITLE
Tests are failing because of test files that are not installed

### ISSUE THREAD

**Issue by kihneman** [enthought/codetools#40] opened 2019-02-22 14:26 UTC
The following codetools tests fail because of missing test files:
```
Assigning floats to arrays ... ERROR
Different sized arrays ... ERROR
Same sized array assignments within 'with' block ... ERROR
```

Here are the error details showing the missing files:
```
IOError: [Errno 2] No such file or directory: '.../site-packages/codetools/contexts/tests/with_mask_codes/test1.py'
IOError: [Errno 2] No such file or directory: '.../site-packages/codetools/contexts/tests/with_mask_codes/test2.py'
IOError: [Errno 2] No such file or directory: '.../site-packages/codetools/contexts/tests/with_mask_codes/test3.py'
```

I was able to make the tests pass by copying the `with_mask_codes` folder from the archive into the `contexts/tests/` folder of the `codetools` installation.

**Comment by rahulporuri** [comment] 2019-02-22 14:54
#36 fixes this issue

**Comment by mdickinson** [comment] 2019-02-22 19:10
Closing; this is a duplicate of #35.

**Closed by mdickinson** 2019-02-22 19:10 UTC
